[secrets]
openai.api_key=["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"]
openai.organization=["org-2AdIkoqVAG3a95CwZLxAwdkE"]
azure.endpoint=["https://datamark-cosmos.documents.azure.com:443/"]
azure.key=["iGAbQK20n5a1LMhHTjb6BtRBzV87v8iGaV7DTZTWb8kZL3lJt91PNF1ZGxuH7PJGqgBpzswKX22TACDblAc3iA=="]